export const RED_COLOR = '#FF0000'
export const BLACK_COLOR = '#000000'

export const ROULETTE_NUMBERS = [
  [
    {
      number: 1,
      color: RED_COLOR,
      betTableOrder: 9,
      wheelOrder: 23,
    },
    {
      number: 2,
      color: BLACK_COLOR,
      betTableOrder: 5,
      wheelOrder: 6,
    },
    {
      number: 3,
      color: RED_COLOR,
      betTableOrder: 1,
      wheelOrder: 35,
    },
    {
      number: 4,
      color: BLACK_COLOR,
      betTableOrder: 10,
      wheelOrder: 4,
    },
    {
      number: 5,
      color: RED_COLOR,
      betTableOrder: 6,
      wheelOrder: 19,
    },
    {
      number: 6,
      color: BLACK_COLOR,
      betTableOrder: 2,
      wheelOrder: 10,
    },
    {
      number: 7,
      color: RED_COLOR,
      betTableOrder: 11,
      wheelOrder: 31,
    },
    {
      number: 8,
      color: BLACK_COLOR,
      betTableOrder: 7,
      wheelOrder: 16,
    },
    {
      number: 9,
      color: RED_COLOR,
      betTableOrder: 3,
      wheelOrder: 27,
    },
    {
      number: 10,
      color: BLACK_COLOR,
      betTableOrder: 12,
      wheelOrder: 18,
    },
    {
      number: 11,
      color: BLACK_COLOR,
      betTableOrder: 8,
      wheelOrder: 14,
    },
    {
      number: 12,
      color: RED_COLOR,
      betTableOrder: 4,
      wheelOrder: 33,
    },
  ],
  [
    {
      number: 13,
      color: BLACK_COLOR,
      betTableOrder: 21,
      wheelOrder: 12,
    },
    {
      number: 14,
      color: RED_COLOR,
      betTableOrder: 17,
      wheelOrder: 25,
    },
    {
      number: 15,
      color: BLACK_COLOR,
      betTableOrder: 13,
      wheelOrder: 2,
    },
    {
      number: 16,
      color: RED_COLOR,
      betTableOrder: 22,
      wheelOrder: 21,
    },
    {
      number: 17,
      color: BLACK_COLOR,
      betTableOrder: 18,
      wheelOrder: 8,
    },
    {
      number: 18,
      color: RED_COLOR,
      betTableOrder: 14,
      wheelOrder: 29,
    },
    {
      number: 19,
      color: RED_COLOR,
      betTableOrder: 23,
      wheelOrder: 3,
    },
    {
      number: 20,
      color: BLACK_COLOR,
      betTableOrder: 19,
      wheelOrder: 24,
    },
    {
      number: 21,
      color: RED_COLOR,
      betTableOrder: 15,
      wheelOrder: 5,
    },
    {
      number: 22,
      color: BLACK_COLOR,
      betTableOrder: 24,
      wheelOrder: 28,
    },
    {
      number: 23,
      color: RED_COLOR,
      betTableOrder: 20,
      wheelOrder: 17,
    },
    {
      number: 24,
      color: BLACK_COLOR,
      betTableOrder: 16,
      wheelOrder: 20,
    },
  ],
  [
    {
      number: 25,
      color: RED_COLOR,
      betTableOrder: 33,
      wheelOrder: 7,
    },
    {
      number: 26,
      color: BLACK_COLOR,
      betTableOrder: 29,
      wheelOrder: 36,
    },
    {
      number: 27,
      color: RED_COLOR,
      betTableOrder: 25,
      wheelOrder: 11,
    },
    {
      number: 28,
      color: BLACK_COLOR,
      betTableOrder: 34,
      wheelOrder: 32,
    },
    {
      number: 29,
      color: BLACK_COLOR,
      betTableOrder: 30,
      wheelOrder: 30,
    },
    {
      number: 30,
      color: RED_COLOR,
      betTableOrder: 26,
      wheelOrder: 15,
    },
    {
      number: 31,
      color: BLACK_COLOR,
      betTableOrder: 35,
      wheelOrder: 26,
    },
    {
      number: 32,
      color: RED_COLOR,
      betTableOrder: 31,
      wheelOrder: 1,
    },
    {
      number: 33,
      color: BLACK_COLOR,
      betTableOrder: 27,
      wheelOrder: 22,
    },
    {
      number: 34,
      color: RED_COLOR,
      betTableOrder: 36,
      wheelOrder: 9,
    },
    {
      number: 35,
      color: BLACK_COLOR,
      betTableOrder: 32,
      wheelOrder: 34,
    },
    {
      number: 36,
      color: RED_COLOR,
      betTableOrder: 28,
      wheelOrder: 13,
    },
  ],
]
